---
- name: Hardening OS + installation cluster K8s
  hosts: all
  become: true

  roles:
    - os_hardening

- name: Installation du control-plane Kubernetes
  hosts: k8s_master
  become: true

  roles:
    - k8s_cluster

- name: Join des workers au cluster
  hosts: k8s_workers
  become: true

  roles:
    - k8s_cluster
